# Generated by Django 4.2.6 on 2023-10-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_tgusers_remove_cart_user_id_remove_cart_user_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tgusers',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='tgusers',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
