# Generated by Django 4.2.6 on 2023-10-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_tgusers_options_tgusers_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default=1, max_length=555, verbose_name='Фото продукта'),
            preserve_default=False,
        ),
    ]
